-- Bar Refill v1 — internal warehouse → bar stock transfer workflow.
-- Dev-rerunnable migration: drops existing bar refill tables, then recreates them.
-- Compatible with src/services/barRefillService.js field mapping.
-- inventory_item_id uses uuid to match public.inventory_items(id).

drop table if exists public.bar_refill_items cascade;
drop table if exists public.bar_refills cascade;

create table public.bar_refills (
  id bigint generated by default as identity primary key,
  refill_date date not null default current_date,
  status text not null default 'draft',
  created_by text not null default '',
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bar_refills_status_check check (status in ('draft', 'picked', 'cancelled'))
);

create table public.bar_refill_items (
  id bigint generated by default as identity primary key,
  refill_id bigint not null references public.bar_refills (id) on delete cascade,
  inventory_item_id uuid references public.inventory_items (id) on delete set null,
  item_name text not null,
  requested_quantity numeric not null default 0,
  picked_quantity numeric not null default 0,
  unit text not null default '',
  is_picked boolean not null default false,
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists bar_refills_refill_date_idx
  on public.bar_refills (refill_date);

create index if not exists bar_refills_status_idx
  on public.bar_refills (status);

create index if not exists bar_refill_items_refill_id_idx
  on public.bar_refill_items (refill_id);

create index if not exists bar_refill_items_inventory_item_id_idx
  on public.bar_refill_items (inventory_item_id);

create or replace function public.set_bar_refills_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.set_bar_refill_items_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists bar_refills_set_updated_at on public.bar_refills;
drop trigger if exists bar_refill_items_set_updated_at on public.bar_refill_items;

create trigger bar_refills_set_updated_at
  before update on public.bar_refills
  for each row
  execute function public.set_bar_refills_updated_at();

create trigger bar_refill_items_set_updated_at
  before update on public.bar_refill_items
  for each row
  execute function public.set_bar_refill_items_updated_at();

alter table public.bar_refills enable row level security;
alter table public.bar_refill_items enable row level security;

drop policy if exists bar_refills_dev_select_all on public.bar_refills;
drop policy if exists bar_refills_dev_insert_all on public.bar_refills;
drop policy if exists bar_refills_dev_update_all on public.bar_refills;
drop policy if exists bar_refills_dev_delete_all on public.bar_refills;

create policy bar_refills_dev_select_all
  on public.bar_refills
  for select
  to anon, authenticated
  using (true);

create policy bar_refills_dev_insert_all
  on public.bar_refills
  for insert
  to anon, authenticated
  with check (true);

create policy bar_refills_dev_update_all
  on public.bar_refills
  for update
  to anon, authenticated
  using (true)
  with check (true);

create policy bar_refills_dev_delete_all
  on public.bar_refills
  for delete
  to anon, authenticated
  using (true);

drop policy if exists bar_refill_items_dev_select_all on public.bar_refill_items;
drop policy if exists bar_refill_items_dev_insert_all on public.bar_refill_items;
drop policy if exists bar_refill_items_dev_update_all on public.bar_refill_items;
drop policy if exists bar_refill_items_dev_delete_all on public.bar_refill_items;

create policy bar_refill_items_dev_select_all
  on public.bar_refill_items
  for select
  to anon, authenticated
  using (true);

create policy bar_refill_items_dev_insert_all
  on public.bar_refill_items
  for insert
  to anon, authenticated
  with check (true);

create policy bar_refill_items_dev_update_all
  on public.bar_refill_items
  for update
  to anon, authenticated
  using (true)
  with check (true);

create policy bar_refill_items_dev_delete_all
  on public.bar_refill_items
  for delete
  to anon, authenticated
  using (true);
