-- Stock / F&B inventory items for quantity, par level, and supplier tracking.
-- Run in the Supabase SQL editor only if this table does not already exist.
-- Compatible with src/services/inventoryService.js field mapping.

create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  item_name text not null,
  category text not null default '',
  supplier text not null default '',
  unit text not null default '',
  quantity numeric not null default 0,
  minimum_quantity numeric not null default 0,
  cost numeric not null default 0,
  status text not null default 'In Stock',
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists inventory_items_item_name_idx
  on public.inventory_items (item_name);

create index if not exists inventory_items_category_idx
  on public.inventory_items (category);

create index if not exists inventory_items_supplier_idx
  on public.inventory_items (supplier);

create index if not exists inventory_items_status_idx
  on public.inventory_items (status);

create or replace function public.set_inventory_items_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists inventory_items_set_updated_at on public.inventory_items;

create trigger inventory_items_set_updated_at
  before update on public.inventory_items
  for each row
  execute function public.set_inventory_items_updated_at();

-- TEMP DEVELOPMENT ONLY — replace with workspace/auth policies before production.
alter table public.inventory_items enable row level security;

drop policy if exists inventory_items_dev_select_all on public.inventory_items;
drop policy if exists inventory_items_dev_insert_all on public.inventory_items;
drop policy if exists inventory_items_dev_update_all on public.inventory_items;
drop policy if exists inventory_items_dev_delete_all on public.inventory_items;

create policy inventory_items_dev_select_all
  on public.inventory_items
  for select
  to anon, authenticated
  using (true);

create policy inventory_items_dev_insert_all
  on public.inventory_items
  for insert
  to anon, authenticated
  with check (true);

create policy inventory_items_dev_update_all
  on public.inventory_items
  for update
  to anon, authenticated
  using (true)
  with check (true);

create policy inventory_items_dev_delete_all
  on public.inventory_items
  for delete
  to anon, authenticated
  using (true);
