-- Supplier directory for procurement and stock item linking.
-- Run in the Supabase SQL editor only if this table does not already exist.
-- Compatible with src/services/supplierService.js field mapping.

create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  company_name text not null,
  contact_person text not null default '',
  phone text not null default '',
  email text not null default '',
  address text not null default '',
  payment_terms text not null default '',
  delivery_days text not null default '',
  notes text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists suppliers_company_name_idx
  on public.suppliers (company_name);

create index if not exists suppliers_active_idx
  on public.suppliers (active);

create or replace function public.set_suppliers_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists suppliers_set_updated_at on public.suppliers;

create trigger suppliers_set_updated_at
  before update on public.suppliers
  for each row
  execute function public.set_suppliers_updated_at();

-- TEMP DEVELOPMENT ONLY — replace with workspace/auth policies before production.
alter table public.suppliers enable row level security;

drop policy if exists suppliers_dev_select_all on public.suppliers;
drop policy if exists suppliers_dev_insert_all on public.suppliers;
drop policy if exists suppliers_dev_update_all on public.suppliers;
drop policy if exists suppliers_dev_delete_all on public.suppliers;

create policy suppliers_dev_select_all
  on public.suppliers
  for select
  to anon, authenticated
  using (true);

create policy suppliers_dev_insert_all
  on public.suppliers
  for insert
  to anon, authenticated
  with check (true);

create policy suppliers_dev_update_all
  on public.suppliers
  for update
  to anon, authenticated
  using (true)
  with check (true);

create policy suppliers_dev_delete_all
  on public.suppliers
  for delete
  to anon, authenticated
  using (true);
