-- Operational tasks for department-based task boards.
-- Prerequisite: public.employees must already exist with id uuid.
-- Run in the Supabase SQL editor only if this table does not already exist.

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  department text not null,
  department_custom text null,
  assigned_employee_id uuid null references public.employees(id) on delete set null,
  priority text not null default 'normal',
  due_date date not null,
  due_time time null,
  recurrence text not null default 'none',
  notes text not null default '',
  status text not null default 'active',
  completed_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tasks_department_check check (
    department in ('service', 'bar', 'bar_manager', 'fb', 'logistics', 'customers', 'custom')
  ),
  constraint tasks_priority_check check (
    priority in ('normal', 'important', 'urgent')
  ),
  constraint tasks_recurrence_check check (
    recurrence in ('none', 'daily', 'weekly', 'monthly')
  ),
  constraint tasks_status_check check (
    status in ('active', 'completed')
  ),
  constraint tasks_custom_department_name_check check (
    department <> 'custom' or nullif(trim(department_custom), '') is not null
  )
);

create index if not exists tasks_department_idx
  on public.tasks (department);

create index if not exists tasks_due_date_idx
  on public.tasks (due_date);

create index if not exists tasks_status_idx
  on public.tasks (status);

create index if not exists tasks_assigned_employee_id_idx
  on public.tasks (assigned_employee_id);

create or replace function public.set_tasks_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tasks_set_updated_at on public.tasks;

create trigger tasks_set_updated_at
  before update on public.tasks
  for each row
  execute function public.set_tasks_updated_at();
