-- Checklist items for task templates and generated tasks.
-- Prerequisites: public.task_templates and public.tasks must already exist.
-- Run in the Supabase SQL editor only if these tables do not already exist.

create table if not exists public.task_template_checklist_items (
  id bigint generated by default as identity primary key,
  template_id bigint not null references public.task_templates(id) on delete cascade,
  title text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists task_template_checklist_items_template_id_idx
  on public.task_template_checklist_items (template_id);

create index if not exists task_template_checklist_items_template_sort_idx
  on public.task_template_checklist_items (template_id, sort_order);

create table if not exists public.task_checklist_items (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks(id) on delete cascade,
  title text not null,
  is_completed boolean not null default false,
  sort_order integer not null default 0,
  completed_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists task_checklist_items_task_id_idx
  on public.task_checklist_items (task_id);

create index if not exists task_checklist_items_task_sort_idx
  on public.task_checklist_items (task_id, sort_order);

create index if not exists task_checklist_items_is_completed_idx
  on public.task_checklist_items (is_completed);

create or replace function public.set_task_checklist_items_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists task_checklist_items_set_updated_at on public.task_checklist_items;

create trigger task_checklist_items_set_updated_at
  before update on public.task_checklist_items
  for each row
  execute function public.set_task_checklist_items_updated_at();

-- TEMP DEVELOPMENT ONLY — replace with workspace/auth policies before production.
alter table public.task_template_checklist_items enable row level security;
alter table public.task_checklist_items enable row level security;

drop policy if exists task_template_checklist_items_dev_select_all on public.task_template_checklist_items;
drop policy if exists task_template_checklist_items_dev_insert_all on public.task_template_checklist_items;
drop policy if exists task_template_checklist_items_dev_update_all on public.task_template_checklist_items;
drop policy if exists task_template_checklist_items_dev_delete_all on public.task_template_checklist_items;

create policy task_template_checklist_items_dev_select_all
  on public.task_template_checklist_items
  for select
  to anon, authenticated
  using (true);

create policy task_template_checklist_items_dev_insert_all
  on public.task_template_checklist_items
  for insert
  to anon, authenticated
  with check (true);

create policy task_template_checklist_items_dev_update_all
  on public.task_template_checklist_items
  for update
  to anon, authenticated
  using (true)
  with check (true);

create policy task_template_checklist_items_dev_delete_all
  on public.task_template_checklist_items
  for delete
  to anon, authenticated
  using (true);

drop policy if exists task_checklist_items_dev_select_all on public.task_checklist_items;
drop policy if exists task_checklist_items_dev_insert_all on public.task_checklist_items;
drop policy if exists task_checklist_items_dev_update_all on public.task_checklist_items;
drop policy if exists task_checklist_items_dev_delete_all on public.task_checklist_items;

create policy task_checklist_items_dev_select_all
  on public.task_checklist_items
  for select
  to anon, authenticated
  using (true);

create policy task_checklist_items_dev_insert_all
  on public.task_checklist_items
  for insert
  to anon, authenticated
  with check (true);

create policy task_checklist_items_dev_update_all
  on public.task_checklist_items
  for update
  to anon, authenticated
  using (true)
  with check (true);

create policy task_checklist_items_dev_delete_all
  on public.task_checklist_items
  for delete
  to anon, authenticated
  using (true);
