-- Reusable daily operation templates for generating department tasks.
-- Prerequisite: public.tasks should exist before generating tasks from templates.
-- Run in the Supabase SQL editor only if this table does not already exist.

create table if not exists public.task_templates (
  id bigint generated by default as identity primary key,
  title text not null,
  department text not null,
  department_custom text null,
  priority text not null default 'normal',
  default_time time null,
  recurrence text not null default 'daily',
  notes text not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint task_templates_department_check check (
    department in (
      'service',
      'bar',
      'bar_manager',
      'floor_manager',
      'fb',
      'logistics',
      'customers',
      'custom'
    )
  ),
  constraint task_templates_priority_check check (
    priority in ('normal', 'important', 'urgent')
  ),
  constraint task_templates_recurrence_check check (
    recurrence in ('daily', 'weekly', 'monthly')
  ),
  constraint task_templates_custom_department_name_check check (
    department <> 'custom' or nullif(trim(department_custom), '') is not null
  )
);

create index if not exists task_templates_department_idx
  on public.task_templates (department);

create index if not exists task_templates_is_active_idx
  on public.task_templates (is_active);

create or replace function public.set_task_templates_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists task_templates_set_updated_at on public.task_templates;

create trigger task_templates_set_updated_at
  before update on public.task_templates
  for each row
  execute function public.set_task_templates_updated_at();

-- TEMP DEVELOPMENT ONLY — replace with workspace/auth policies before production.
alter table public.task_templates enable row level security;

drop policy if exists task_templates_dev_select_all on public.task_templates;
drop policy if exists task_templates_dev_insert_all on public.task_templates;
drop policy if exists task_templates_dev_update_all on public.task_templates;
drop policy if exists task_templates_dev_delete_all on public.task_templates;

create policy task_templates_dev_select_all
  on public.task_templates
  for select
  to anon, authenticated
  using (true);

create policy task_templates_dev_insert_all
  on public.task_templates
  for insert
  to anon, authenticated
  with check (true);

create policy task_templates_dev_update_all
  on public.task_templates
  for update
  to anon, authenticated
  using (true)
  with check (true);

create policy task_templates_dev_delete_all
  on public.task_templates
  for delete
  to anon, authenticated
  using (true);
